# This is the main pipeline which determines which environment you will deploy too

# parameter for environment either dev/tst/acc or prd
parameters:
- name: environment
  type: string

# parameters for resources
- name: deployUnami
  type: boolean
- name: deployKeyVault
  type: boolean
- name: deployStorage
  type: boolean
- name: deployVM
  type: boolean
- name: deploySynapse
  type: boolean
- name: deployAcces
  type: boolean
- name: deploySparkPool
  type: boolean

pool:
  vmImage: ubuntu-latest

# deployment environments
stages:

# deployment of BICEP template to dev
- ${{ if eq(parameters.environment, "dev") }}:

  # pass parameters for bicep templates
      - template: resource-pipelines.yml
        parameters:
          environmentType: parameters.environment
          deployUnami: ${{parameters.deployUnami}}
          deployKeyVault: ${{parameters.deployKeyVault}}
          deployVM: ${{parameters.deployVM}}
          deploySynapse: ${{parameters.deploySynapse}}
          deployAcces: ${{parameters.deployAcces}}
          deploySparkPool: ${{parameters.deploySparkPool}}

# deployment of BICEP template to tst
- ${{ if eq(parameters.environment, "tst") }}:

  # pass parameters for bicep templates
      - template: resource-pipelines.yml
        parameters:
          environmentType: parameters.environment
          deployUnami: ${{parameters.deployUnami}}
          deployKeyVault: ${{parameters.deployKeyVault}}
          deployVM: ${{parameters.deployVM}}
          deploySynapse: ${{parameters.deploySynapse}}
          deployAcces: ${{parameters.deployAcces}}
          deploySparkPool: ${{parameters.deploySparkPool}}

# deployment of BICEP template to acc
- ${{ if eq(parameters.environment, "acc") }}:

  # pass parameters for bicep templates
      - template: resource-pipelines.yml
        parameters:
          environmentType: parameters.environment
          deployUnami: ${{parameters.deployUnami}}
          deployKeyVault: ${{parameters.deployKeyVault}}
          deployVM: ${{parameters.deployVM}}
          deploySynapse: ${{parameters.deploySynapse}}
          deployAcces: ${{parameters.deployAcces}}
          deploySparkPool: ${{parameters.deploySparkPool}}


# deployment of BICEP template to prd
- ${{ if eq(parameters.environment, "prd") }}:

  # pass parameters for bicep templates
      - template: resource-pipelines.yml
        parameters:
          environmentType: parameters.environment
          deployUnami: ${{parameters.deployUnami}}
          deployKeyVault: ${{parameters.deployKeyVault}}
          deployVM: ${{parameters.deployVM}}
          deploySynapse: ${{parameters.deploySynapse}}
          deployAcces: ${{parameters.deployAcces}}
          deploySparkPool: ${{parameters.deploySparkPool}}