# Start de resource YML pipeline

# parameters included resources
# parameters for environment to deploy to
parameters:
- name: environment
  type: string
- name: deployUnami
  type: boolean
- name: deployKeyVault
  type: boolean
- name: deployStorage
  type: boolean


stages: 

 # if included unami run the user assigned management identity pipeline
- ${{ if eq(parameters.deployStorage, false) }}:
  - template: resources/unami.yml
    parameters:
      environmentType: ${{parameters.environmentType}}

 # if included key vault run the key vault pipeline
- ${{ if eq(parameters.deployStorage, false) }}:
  - template: resources/keyvault.yml
    parameters:
      environmentType: ${{parameters.environmentType}}

 # if included storage run the storage pipeline
- ${{ if eq(parameters.deployStorage, false) }}:
  - template: resources/storage.yml
    parameters:
      environmentType: ${{parameters.environmentType}}

  
