# Start de resource YML pipeline

# parameters included resources
# parameters for environment to deploy to
parameters:
- name: environment
  type: string
- name: deployStorage
  type: boolean


stages: 

 # if included storage run the storage pipeline
- ${{ if eq(parameters.deployStorage, false) }}:
  - template: resources/storage.yml
    parameters:
      environmentType: ${{parameters.environmentType}}
